<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		<?php
			echo $this->headTitle();
		?>
		
		<link href='<?php echo'/application/templates/default/default/css/bootstrap.min.css';?>' rel='stylesheet' type='text/css'>
		<link href='<?php echo'/application/templates/default/default/plugin/jqueryui/jquery-ui.min.css';?>' rel='stylesheet' type='text/css'>
		<link href='<?php echo'/application/templates/default/default/plugin/jqueryui/jquery-ui-1.10.3.flat.min.css';?>' rel='stylesheet' type='text/css'>
		<link href="<?php echo "/application/templates/default/default/font-awesome-4.1.0/css/font-awesome.min.css"?>" rel="stylesheet" type="text/css">
		<link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
		<link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
		<script src='<?php echo'/application/templates/default/default/js/jquery.min.js';?>' type='text/javascript'></script>
	</head>
	<body>
		
		<?php
			echo $this->layout()->content;	
		?>
		
	
		<script src='<?php echo'/application/templates/default/default/js/bootstrap.min.js';?>' type='text/javascript'></script>
		<script src="<?php echo'/application/templates/default/default/js/jquery.easing.min.js';?>"></script>
		<script src='<?php echo'/application/templates/default/default/plugin/jqueryui/jquery-ui.min.js';?>' type='text/javascript'></script>
		<script src='<?php echo'/application/templates/default/default/js/fileshare.js';?>' type='text/javascript'></script>
		<script src='<?php echo'/application/templates/default/default/js/valid_register.js';?>' type='text/javascript'></script>
	</body>
</html>